<?php

/**
 * Created by PhpStorm.
 * User: IME
 * Date: 27.04.2017
 * Time: 0:43
 */
class Model_Admin extends Data_Model
{

    public function __construct() {
        parent::__construct();
    }

    public function get_data($param = null)
    {
        if (!isset($_SESSION)){
            session_start();
        }
        $_SESSION['sort']=Model::ID;
        if (!$_SESSION['auth']){
            header('Location: /auth/');
            return;
        }
        $data=parent::get_data($param); // TODO: Change the autogenerated stub
        $_SESSION['auth'] = true;
        return $data;
    }

    public function create()
    {
        $id=strip_tags($_POST['id']);
        if (isset($_POST['is-done'])){
            $is_done=true;
        }else{
            $is_done=false;
        }
        $text=strip_tags($_POST['text']);
        //login verify
        $sth = $this->db->prepare("UPDATE `tasks` SET `text`=:text, `is_done`=:is_done WHERE `id`=:id;");
        //create data array for query
        $data = array(
            'id' => $id,
            'text' => $text,
            'is_done' => $is_done
        );
        $state = $sth->execute($data);
        return $_POST['page'];
    }

}